<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\test\BlaisePascal.Example.DomainTests\BlaisePascal.Example.DomainTests.csproj" />
    <ProjectReference Include="..\BlaisePascal.Example.Domain\BlaisePascal.Example.Domain.csproj" />
  </ItemGroup>

</Project>
